export const styles = {
    container: {
      maxWidth: '1000px',
      margin: '0 auto',
      padding: '40px 20px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    header: {
      textAlign: 'center' as const,
      color: '#1a1a1a',
      fontSize: '2.5rem',
      marginBottom: '2rem',
      fontWeight: '700',
      background: 'linear-gradient(45deg, #2196F3, #4CAF50)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
    section: {
      backgroundColor: 'white',
      borderRadius: '12px',
      padding: '24px',
      marginBottom: '32px',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
    sectionTitle: {
      fontSize: '1.5rem',
      color: '#1a1a1a',
      marginBottom: '1.5rem',
      fontWeight: '600',
    },
    userList: {
      listStyle: 'none',
      padding: 0,
      display: 'grid',
      gap: '12px',
    },
    userItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '16px',
      backgroundColor: '#f8f9fa',
      borderRadius: '8px',
      transition: 'all 0.2s ease',
      border: '1px solid #e9ecef',
      '&:hover': {
        transform: 'translateY(-2px)',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      },
    },
    userInfo: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '4px',
    },
    userName: {
      fontSize: '1.1rem',
      fontWeight: '600',
      color: '#1a1a1a',
    },
    userEmail: {
      fontSize: '0.9rem',
      color: '#666',
    },
    button: {
      padding: '8px 16px',
      backgroundColor: '#2196F3',
      color: 'white',
      border: 'none',
      borderRadius: '6px',
      cursor: 'pointer',
      fontSize: '0.9rem',
      fontWeight: '500',
      transition: 'all 0.2s ease',
      '&:hover': {
        backgroundColor: '#1976D2',
        transform: 'translateY(-1px)',
      },
      '&:disabled': {
        backgroundColor: '#ccc',
        cursor: 'not-allowed',
        transform: 'none',
      },
    },
    form: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '24px',
      maxWidth: '500px',
      margin: '0 auto',
    },
    formGroup: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '8px',
      position: 'relative' as const,
    },
    label: {
      fontSize: '0.95rem',
      fontWeight: '600',
      color: '#2c3e50',
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
    },
    requiredMark: {
      color: '#dc3545',
      fontSize: '1.2rem',
      lineHeight: '1',
    },
    input: {
      padding: '12px 16px',
      borderRadius: '8px',
      border: '2px solid #e9ecef',
      fontSize: '1rem',
      transition: 'all 0.2s ease',
      backgroundColor: '#f8f9fa',
      '&:focus': {
        outline: 'none',
        borderColor: '#2196F3',
        backgroundColor: 'white',
        boxShadow: '0 0 0 3px rgba(33, 150, 243, 0.1)',
      },
      '&::placeholder': {
        color: '#adb5bd',
      },
    },
    submitButton: {
      padding: '12px 24px',
      backgroundColor: '#2196F3',
      color: 'white',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      fontSize: '1rem',
      fontWeight: '600',
      transition: 'all 0.2s ease',
      marginTop: '8px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '8px',
      '&:hover': {
        backgroundColor: '#1976D2',
        transform: 'translateY(-1px)',
        boxShadow: '0 4px 12px rgba(33, 150, 243, 0.2)',
      },
      '&:disabled': {
        backgroundColor: '#e9ecef',
        color: '#adb5bd',
        cursor: 'not-allowed',
        transform: 'none',
        boxShadow: 'none',
      },
    },
    formTitle: {
      fontSize: '1.5rem',
      color: '#2c3e50',
      marginBottom: '24px',
      fontWeight: '700',
      textAlign: 'center' as const,
      position: 'relative' as const,
      '&::after': {
        content: '""',
        position: 'absolute' as const,
        bottom: '-12px',
        left: '50%',
        transform: 'translateX(-50%)',
        width: '60px',
        height: '4px',
        backgroundColor: '#2196F3',
        borderRadius: '2px',
      },
    },
    successMessage: {
      backgroundColor: '#d4edda',
      color: '#155724',
      padding: '12px',
      borderRadius: '8px',
      marginTop: '16px',
      fontSize: '0.9rem',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    error: {
      color: '#dc3545',
      margin: '8px 0',
      fontSize: '0.9rem',
      padding: '8px',
      backgroundColor: '#fff5f5',
      borderRadius: '4px',
      border: '1px solid #ffcdd2',
    },
    loading: {
      color: '#666',
      textAlign: 'center' as const,
      padding: '20px',
      fontSize: '1rem',
    },
    userDetails: {
      marginTop: '24px',
      padding: '20px',
      backgroundColor: '#f8f9fa',
      borderRadius: '8px',
      border: '1px solid #e9ecef',
    },
    userDetailsTitle: {
      fontSize: '1.2rem',
      fontWeight: '600',
      marginBottom: '16px',
      color: '#1a1a1a',
    },
    userDetailsInfo: {
      display: 'grid',
      gap: '12px',
    },
    userDetailsItem: {
      display: 'flex',
      gap: '8px',
      '& strong': {
        fontWeight: '600',
        color: '#1a1a1a',
        minWidth: '60px',
      },
    },
    mainContent: {
      display: 'grid',
      gridTemplateColumns: '1fr 400px',
      gap: '32px',
      alignItems: 'start',
    },
    usersSection: {
      backgroundColor: 'white',
      borderRadius: '12px',
      padding: '24px',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
    formSection: {
      backgroundColor: 'white',
      borderRadius: '12px',
      padding: '32px',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
      position: 'sticky' as const,
      top: '24px',
      transition: 'all 0.3s ease',
      '&:hover': {
        boxShadow: '0 8px 16px rgba(0, 0, 0, 0.1)',
      },
    },
    buttonGroup: {
      display: 'flex',
      gap: '8px',
    },
    deleteButton: {
      padding: '8px 16px',
      backgroundColor: '#dc3545',
      color: 'white',
      border: 'none',
      borderRadius: '6px',
      cursor: 'pointer',
      fontSize: '0.9rem',
      fontWeight: '500',
      transition: 'all 0.2s ease',
      '&:hover': {
        backgroundColor: '#c82333',
        transform: 'translateY(-1px)',
      },
    },
  };